from flask import Flask, request, jsonify
import requests
import json
import threading
from flask_cors import CORS
from dotenv import load_dotenv
import os
load_dotenv()

app = Flask(__name__)
CORS(app)

api_key = os.getenv("API_KEY")

def get_response(question, results, index):
    response = requests.post(
        url="https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": "Bearer " + api_key,
        },
        data=json.dumps({
            "model": "google/gemini-2.0-flash-001",
            "messages": [
                {"role": "user", "content": question}
            ]
        })
    )
    results[index] = json.loads(response.json()["choices"][0]["message"]["content"][8:-4])

@app.route('/generate_guide', methods=['POST'])
def ask_questions():
    required_keys = ["company_name", "job_role", "job_description","resume"]
    data = request.json
    if all(key in data for key in required_keys):
        pass   
    else:
        return {"error": "Missing keys"}, 400
    
    prompts = [
        "Analyze the provided Company Name ("+data['company_name']+") and the context from the Job Description ("+data["job_description"]+"). Your goal is to generate a comprehensive yet concise research dossier tailored for a "+data["job_role"]+" role preparing for an interview at this specific company. Please gather information from reliable public sources (like the company's official website, reputable news outlets, financial reports if public).Structure the output into the distinct sections listed below. Present detailed information using bullet points or short paragraphs as appropriate. Ensure the output is cleanly formatted and ready to populate UI cards.---REQUIRED SECTIONS:1. Company Overview • Summary of the company in 1 line • What are their main products/services? • What's their core business model and value proposition? • When were they founded, and what are some key historical milestones? • What's their current market position? 2. Mission & Culture • What are the company's official mission and vision statements? • What are their stated core values? 3. Target Market & Customers • Who are their primary customers (B2B, B2C, specific industries)? • What industries/verticals do they serve? • Any notable public clients?  4. Size & Structure • Approximately how many employees? • Estimated revenue (if public)? • Are they public or private? • Do they have parent companies or subsidiaries? 5. Leadership • Who are the key executives (especially CEO, CPO/Head of Product)? 6. Competitive Landscape • 3–5 main competitors? • What is the company's Unique Selling Proposition or key differentiator? • What are their competitive advantages? 7. Recent News & Developments • Major announcements, product updates, M&A, or partnerships in the last 6–12 months? 8. Industry Trends • What key trends affect the sector they operate in? • How might these represent opportunities or threats?9. Funding/Financial Health • Recent funding history (if private)?• General financial health (if public)?.also search on the entire web and Result should contain all sub modules and it is fixed : Company Overview, Mission & Culture, Target Market & Customers, Size & Structure, Leadership, Competitive Landscape, Recent News & Developments, Industry Trends, Funding/Financial Health. And give me output only in this JSON format only and this is JSON data of 'COMPANY RESEARCH' only and provide me entire full json data and not half:[{title:'Company Overview',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Mission & Culture',summary:'',content:'',points:[]}\\}...",
        "Analyze the product or service mentioned in the provided Job Description ("+data["job_description"]+") for the company ("+data["company_name"]+"). Your goal is to generate a structured, comprehensive analysis to help a "+data["job_role"]+" role prepare for an interview related to this product. Please base your research on reliable public sources such as the company's official website, product pages, press releases, and reputable industry news outlets.REQUIRED SECTIONS: 1. CORE OFFERING • What does the product actually do (primary functionality)? • What key customer pain points does it solve? • What is the value proposition — why do users choose this? 2. MARKET POSITION • Who are the product's target customers? • Who are the main competitors (direct/indirect)? • What makes it unique — key differentiators? 3. TECHNICAL FOUNDATION • What kind of platform is it (SaaS, mobile app, API, etc.)? • What technologies or frameworks are used (if known)? • What's the general architectural approach or model? 4. BUSINESS APPROACH • How does the company monetize the product (revenue model)? • What are the latest features, releases, or updates? • Are there any public roadmaps or future direction hints?"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : Core Offering, Market Position, Technical Foundation, Business Approach. And give me output only in this JSON format only and this is JSON data of 'PRODUCT RESEARCH' only and provide me entire full json data and not half:[{title:'Core Offering',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Market Position',summary:'',content:'',points:[]}\\}...",
        "Analyze the provided Job Description ("+data["job_description"]+") for the company ("+data["company_name"]+")"+". Your goal is to provide a structured analysis of the role's key elements to help a "+data["job_role"]+" role  understand the specific requirements and expectations for the job. Base your analysis primarily on the details within the provided Job Description and offer insights in the following sections: --- REQUIRED SECTIONS: 1. CORE RESPONSIBILITIES • What are the key responsibilities of the role? • What are the primary tasks or goals the person will be responsible for in this position? 2. REQUIRED SKILLS • What technical skills and tools are required for the job (specific software, platforms, technologies)? • What methodologies (e.g., Agile, Scrum, etc.) does the role expect experience with? • What are the experience requirements (years in role/industry)? • What essential soft skills are important (e.g., communication, leadership)? 3. PREFERRED QUALIFICATIONS • What are the 'nice-to-have' skills or experience? • What differentiators would make a candidate stand out for this role? 4. SUCCESS METRICS • How will performance be measured for this role? • What impact areas and outcomes are expected? 5. TEAM STRUCTURE • Who are the key stakeholders and collaborators the person in this role will work with? "+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : Core Responsibilities, Required Skills, Preferred Qualifications, Success Metrics, Team Structure. And give me output only in this JSON format only and this is JSON data of 'Job Description Analysis' only and provide me entire full json data and not half:[{title:'Core Responsibilities',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Required Skills',summary:'',content:'',points:[]}\\n}...",
        "Generate a recruiter interview preparation guide tailored for "+data["job_role"]+" position, based on the provided Job Description ("+data["job_description"]+") and Candidate Resume ("+data["resume"]+"). Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : Background and Experience, Technical Knowledge, Role-Specific Competencies, Leadership and Collaboration, Company & Product Knowledge Section, Career Vision, General Questions, Questions for Recruiter on Team Structure, Questions for Recruiter on Role Responsibilities, Questions for Recruiter on Company Environment, Questions for Recruiter on Role Purpose, Questions for Recruiter on JD Points. And give me output only in this JSON format only and this is JSON data of 'Recruiter Screen Preparation' only and provide me entire full json data and not half:[{title:'Background and Experience',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Technical Knowledge',summary:'',content:'',points:[]}\\}...",
        "Generate a tailored set of potential interview questions for a "+data["job_role"]+" role Hiring Manager round, based on the provided Job Description "+data["job_description"]+") and Candidate Resume ("+data["resume"]+") . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : Phase 1: Introduction & Background, Phase 2: Product Experience Deep Dives, Phase 3: Product Methodology Assessment, Phase 4: Cross-Functional Collaboration, Phase 5: Strategic Thinking, Phase 6: Technical Understanding, Phase 7: Role-Specific Challenges. And give me output only in this JSON format only and this is JSON data of 'Recruiter Screen Preparation' only and provide me entire full json data and not half:[{title:'Phase 1: Introduction & Background',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Phase 2: Product Experience Deep Dives',summary:'',content:'',points:[]}\\}...",
        "Generate 15 behavioral questions that focus on: leadership, conflict resolution, failure recovery, crossfunctional collaboration, Decision Making, Communication style, prioritization style for this job description "+data["job_description"]+") Do not mention the category just the questions"+". Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : STAR Method for Behavioral Questions,Essential Behavioral Interview Questions Decision Making & Problem Solving, Taking Initiative, Customer/Client Focus, Teamwork & Collaboration, Leadership, Adaptability, Results & Accountability, Innovation & Creativity, Communication, Integrity & Ethics. And give me output only in this JSON format only and this is JSON data of 'Behavioral Interview' only and provide me entire full json data and not half:[{title:'STAR Method for Behavioral Questions',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Essential Behavioral Interview Questions Decision Making & Problem Solving',summary:'',content:'',points:[]}\\}...",
        "Analyze the resume ("+data["resume"]+") and Job Description ("+data["job_description"]+") and identify the best experiences or skill to highlight to stand out and show the interviewer that you are good fit for the job"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Resume Experience to highlight To stand out' only and provide me entire full json data and not half:[{title:'some important title..',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'some important title...',summary:'',content:'',points:[]}\\}...",
        "You're being asked 'What is your favorite product?' and 'How would you improve your favorite product?' in an interview setting. Your goal is to provide insightful answers that showcase your analytical skills, user-centric thinking, and potential for innovation"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. Result should contain all sub modules and it is fixed : Choose Thoughtfully,Explain Your Choice, Focus on Improvement, Justify Your Suggestions, Keep it Concise and Positive. And give me output only in this JSON format only and this is JSON data of 'Favorite Product Question' only and provide me entire full json data and not half:[{title:'Choose Thoughtfully',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Explain Your Choice',summary:'',content:'',points:[]}\\}...",
        "Generate 5 Product Design type question for a ("+data["job_role"]+") interview based on the company’s industry or product type mentioned in the JD (."+data["job_description"]+")"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Product Design' only and provide me entire full json data and not half:[{title:'Important title text',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Important title text',summary:'',content:'',points:[]}\\}...",
        "Generate 4-6 analytical interview questions suitable for a "+data["job_role"]+" role at a company ("+data["company_name"]+") and job description ("+data["job_description"]+"). The questions should be composed of: **2-3 Analytical Questions:**, **2-3 A/B Testing Scenarios:**"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly.And give me output only in this JSON format only and this is JSON data of 'Product Sense' only and provide me entire full json data and not half:[{title:'Important title text',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'Important title text',summary:'',content:'',points:[]}\\}...",
        "'Analyze the Company name ("+data['company_name']+") and Job Description ("+data['job_description']+") and Generate 7 strategic product questions for a ("+data["job_role"]+") role at ("+data["company_name"]+"). Company: ("+data["company_name"]+") Product: ... Industry: ... Competitors: ... Mix of question types: - Product investment: 'Why should ("+data["company_name"]+") continue investing in product?' - Competitive strategy: 'How would you respond to competitor's new features?' - Market expansion: 'Should ("+data["company_name"]+") enter new market?' - Metrics & goals: 'What metrics would you track for product?' - Industry trends: 'How should ("+data["company_name"]+") adapt to industry trend ?' Make questions specific to real products, competitors, and industry challenges. '+' . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Product Strategy' only and provide me entire full json data and not half in this format only :[{title:'some important title..',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'some important title...',summary:'',content:'',points:[]}\\}...",
        "Analyze the Company name ("+data["company_name"]+") and Job Description ("+data["job_description"]+") and Generate a list of market sizing interview questions that test a candidate's estimation and analytical skills. Guidelines • Focus on strategic understanding and market potential • Cover diverse industries and technologies Question Types 1. Total Addressable Market (TAM) estimates 2. Revenue potential calculations 3. User base or adoption rate projections 4. Infrastructure and operational cost estimations"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Product Strategy' only and provide me entire full json data and not half in this format only :[{title:'some important title..',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'some important title...',summary:'',content:'',points:[]}\\}...",
        "Analyze the Company name ("+data["company_name"]+") and Job Description ("+data["job_description"]+") and resume ("+data["resume"]+") and generate a comprehensive list of technical interview questions that probe the candidate's expertise in key areas mentioned in the job description. Please list all questions as a single, flat list. No grouping or labels. Question types: high level understanding based questions on key technical concepts mentioned in JD Experience-based scenario questions (based on resume) The candidate’s experience collaborating with engineers Their understanding of technical trade-offs, implementation complexity, or API design Probing questions about past projects that demonstrate proficiency"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Product Strategy' only and provide me entire full json data and not half in this format only :[{title:'some important title..',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'some important title...',summary:'',content:'',points:[]}\\}...",
        "Analyze the Company name ("+data["company_name"]+") and Job Description ("+data["job_description"]+") and resume ("+data["resume"]+") and generate a list of 15 leadership interview questions that assess the candidate's ability to lead and influence. Please list all questions as a single, flat list. No grouping or labels. Question types: Strategic vision and alignment with company goals Experience managing crossfunctional stakeholders Decision-making and prioritization approaches Team leadership and development capabilities Communication and influence strategies Handling organizational challenges and change"+" . Add more points,values, etc. as per your understanding and I want json data to be more so add accordingly. And give me output only in this JSON format only and this is JSON data of 'Product Strategy' only and provide me entire full json data and not half in this format only :[{title:'some important title..',summary:'',content:'some text content only',points:[{main:'title of point can be short text or little long short text',subPoints:['value1 can be text only','value2',..]},{main:'',subPoints:['value1',..]},..]},{title:'some important title...',summary:'',content:'',points:[]}\\}..."
        ]
    results = [None, None,None,None,None,None, None,None,None,None,None, None,None,None]
    threads = []

    for i, prompt in enumerate(prompts):
        thread = threading.Thread(target=get_response, args=(prompt, results, i))
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    return jsonify({
        "company_research": results[0],
        "product_research": results[1],
        "job_description_analysis": results[2],
        "recruiter_screen_preparation": results[3],
        "hiring_manager_round": results[4],
        "behavioral_interview": results[5],
        "resume_experience_to_highlight_to_stand_out": results[6],
        "favorite_product_question": results[7],
        "product_design": results[8],
        "product_sense": results[9],
        "product_strategy": results[10],
        "analytical_estimation": results[11],
        "technical": results[12],
        "leadership": results[13]
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
    # app.run(debug=True)